import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { CreateConversationDto } from './dto/create-conversation.dto';
import { UpdateConversationDto } from './dto/update-conversation.dto';

@Injectable()
export class ConversationsService {
  constructor(private prisma: PrismaService) {}

  // Create new conversation
  async create(userId: number, title?: string) {
    return this.prisma.conversation.create({
      data: {
        userId,
        title: title || 'Nouvelle conversation',
      },
    });
  }

  // Get all conversations for user (with pagination)
  async findAllByUser(userId: number, skip = 0, take = 20) {
    const [conversations, total] = await Promise.all([
      this.prisma.conversation.findMany({
        where: { userId },
        include: {
          messages: {
            orderBy: { timestamp: 'desc' },
            take: 1,
          },
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take,
      }),
      this.prisma.conversation.count({ where: { userId } }),
    ]);

    return { conversations, total };
  }

  // Get conversation with all messages
  async findOne(id: number, userId: number) {
    return this.prisma.conversation.findFirstOrThrow({
      where: { id, userId },
      include: {
        messages: {
          orderBy: { timestamp: 'asc' },
        },
      },
    });
  }

  // Update conversation (title, pin status)
  async update(id: number, userId: number, dto: UpdateConversationDto) {
    return this.prisma.conversation.update({
      where: { id, userId },
      data: dto,
    });
  }

  // Delete conversation
  async delete(id: number, userId: number) {
    return this.prisma.conversation.delete({
      where: { id, userId },
    });
  }

  // Add message to conversation
  async addMessage(
    conversationId: number,
    userId: number,
    role: string,
    question: string | null,
    response: string,
    sqlGenerated?: string,
    data?: any,
  ) {
    // Verify conversation belongs to user
    const conversation = await this.prisma.conversation.findFirstOrThrow({
      where: { id: conversationId, userId },
    });

    const message = await this.prisma.conversationMessage.create({
      data: {
        conversationId,
        role,
        question,
        response,
        sqlGenerated,
        data,
      },
    });

    // Increment question count on assistant response
    if (role === 'assistant') {
      await this.prisma.conversation.update({
        where: { id: conversationId },
        data: {
          questionCount: { increment: 1 },
          updatedAt: new Date(),
        },
      });
    }

    return message;
  }

  // Update conversation title (auto-generated by LLM)
  async updateTitle(id: number, userId: number, title: string) {
    return this.prisma.conversation.update({
      where: { id, userId },
      data: { title },
    });
  }

  // Toggle pin status
  async togglePin(id: number, userId: number) {
    const conversation = await this.prisma.conversation.findFirstOrThrow({
      where: { id, userId },
    });

    return this.prisma.conversation.update({
      where: { id },
      data: { isPinned: !conversation.isPinned },
    });
  }
}
